[package]
authors = ["David Peter <mail@david-peter.de>"]
categories = ["command-line-utilities"]
description = "A command-line benchmarking tool"
homepage = "https://github.com/sharkdp/hyperfine"
license = "MIT/Apache-2.0"
name = "hyperfine"
readme = "README.md"
repository = "https://github.com/sharkdp/hyperfine"
version = "1.5.0"

[dependencies]
colored = "1.6"
indicatif = "0.9"
statistical = "0.1"
atty = "0.2.2"
cfg-if = "0.1.6"
csv = "1.0.0"
serde = "1.0.82"
serde_derive = "1.0.82"
serde_json = "1.0.33"

[target.'cfg(not(windows))'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.4", features = ["processthreadsapi", "minwindef", "winnt"] }

[dependencies.clap]
version = "2"
default-features = false
features = ["suggestions", "color", "wrap_help"]

[dev-dependencies]
approx = "0.3"
