[package]
authors = ["David Peter <mail@david-peter.de>"]
categories = ["command-line-utilities"]
description = "A command-line benchmarking tool"
homepage = "https://github.com/sharkdp/hyperfine"
license = "MIT/Apache-2.0"
name = "hyperfine"
readme = "README.md"
repository = "https://github.com/sharkdp/hyperfine"
version = "1.13.0"
edition = "2018"
build = "build.rs"

[dependencies]
colored = "2.0"
indicatif = "0.16"
statistical = "1.0"
atty = "0.2"
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rust_decimal = "1.19"
rand = "0.8"
shell-words = "1.0"
thiserror = "1.0"
anyhow = "1.0"

[target.'cfg(not(windows))'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["processthreadsapi", "minwindef", "winnt"] }

[dependencies.clap]
version = "3"
default-features = false
features = ["suggestions", "color", "wrap_help", "cargo"]

[dev-dependencies]
approx = "0.5"
assert_cmd = "2.0"
predicates = "2.1"
tempfile = "3.3"

[build-dependencies]
clap = "3"
atty = "0.2"
clap_complete = "3"

[profile.release]
lto = true
