[package]
authors = ["David Peter <mail@david-peter.de>"]
categories = ["command-line-utilities"]
description = "A command-line benchmarking tool"
homepage = "https://github.com/sharkdp/hyperfine"
license = "MIT/Apache-2.0"
name = "hyperfine"
readme = "README.md"
repository = "https://github.com/sharkdp/hyperfine"
version = "1.11.0"
edition = "2018"
build = "build.rs"

[dependencies]
colored = "2.0"
indicatif = "0.16"
statistical = "1.0"
atty = "0.2"
cfg-if = "1.0"
csv = "1.1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rust_decimal = "1.15"
rand = "0.8"

[target.'cfg(not(windows))'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["processthreadsapi", "minwindef", "winnt"] }

[dependencies.clap]
version = "2"
default-features = false
features = ["suggestions", "color", "wrap_help"]

[dev-dependencies]
approx = "0.5"

[build-dependencies]
clap = "2"
version_check = "0.9"
atty = "0.2"

[profile.release]
lto = true
