[package]
authors = ["David Peter <mail@david-peter.de>"]
categories = ["command-line-utilities"]
description = "A command-line benchmarking tool"
homepage = "https://github.com/sharkdp/hyperfine"
license = "MIT/Apache-2.0"
name = "hyperfine"
readme = "README.md"
repository = "https://github.com/sharkdp/hyperfine"
version = "1.5.0"
edition = "2018"

[dependencies]
colored = "1.8"
indicatif = "0.11"
statistical = "1.0"
atty = "0.2.2"
cfg-if = "0.1.9"
csv = "1.0.7"
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0.39"

[target.'cfg(not(windows))'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.7", features = ["processthreadsapi", "minwindef", "winnt"] }

[dependencies.clap]
version = "2"
default-features = false
features = ["suggestions", "color", "wrap_help"]

[dev-dependencies]
approx = "0.3"
